allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

// SOLUCIÓN PARA ISAR, PLUGINS Y OBSOLESCENCIA DE JAVA
subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    namespace = project.group
                }

                // Forzamos la versión del SDK para todos los plugins que lo requieran
                compileSdk = 36

                // Forzamos Java 17 en todos los plugins y subproyectos de forma segura
                compileOptions {
                    sourceCompatibility = JavaVersion.VERSION_17
                    targetCompatibility = JavaVersion.VERSION_17
                }

                // Ajustamos Kotlin si está presente dentro del bloque android
                if (project.plugins.hasPlugin('kotlin-android')) {
                    kotlinOptions {
                        jvmTarget = "17"
                    }
                }
            }
        }
    }
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
